# Generated by Django 4.2.7 on 2023-12-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='is_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='in_draw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.draw'),
        ),
    ]
