# Generated by Django 4.2.7 on 2023-12-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_participant_2_pairing_giftee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='has_drawn',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='was_drawn',
        ),
    ]
